spring:
  datasource:
    password: 0637490353pimaua
    url: jdbc:mysql://localhost:3306/homework_39
    username: root

logging:
  file.name: src/logs/dev_app.log
  level:
    org.springframework.web: INFO
    org.springframework.web.controller: INFO
    org.springframework.web.entities: INFO
    org.springframework.web.repository: INFO
    org.springframework.web.service: INFO
    org.springframework.web.security: INFO
    org.springframework.web.exception_handling: INFO

